# Generated by Django 6.0 on 2026-03-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="emoji",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
