# Generated by Django 6.0 on 2026-03-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0004_course_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
