# Generated by Django 6.0 on 2026-03-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0006_alter_course_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="videos/")),
            ],
        ),
    ]
