# Generated by Django 6.0 on 2026-03-24 11:16

import utils.validator
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="ticket/%Y/%m/",
                validators=[utils.validator.validate_attachment],
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="attachment",
            field=models.FileField(
                blank=True,
                upload_to="ticket/%Y/%m/",
                validators=[utils.validator.validate_attachment],
            ),
        ),
    ]
