# Generated by Django 6.0 on 2026-03-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="picture",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="quiz/"
            ),
        ),
    ]
