# Generated by Django 6.0 on 2026-03-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0002_alter_question_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="picture",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="quiz/"
            ),
        ),
    ]
