name: Frontend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest' # Or pin to a specific version like '1.1.0'

      - name: Install dependencies
        run: bun install

      - name: Run Linter
        run: bun run lint

      - name: Build Application
        run: bun run build